config { type: "test", dataset: "top_ten_zipcodes_by_population"}


input "population_by_zip_2000" {
    SELECT "33143" AS zipcode, 1 AS population
    UNION ALL
    SELECT "33143" AS zipcode, 4 AS population
}

input "population_by_zip_2010" {
    SELECT "33143" AS zipcode, 1 AS population
    UNION ALL
    SELECT "33143" AS zipcode, 3 AS population
}

SELECT 2000 AS year, "33143" AS zipcode, 5 AS population
UNION ALL
SELECT 2010 AS year, "33143" AS zipcode, 4 AS population