pipeline {
    agent { any { image 'python:3.8.0' } }
    stages {
        stage('install_requirements') {
            steps {
                sh 'python3 -m venv venv'
                sh 'venv/bin/python3 -m pip install --upgrade pip'
                sh 'source venv/bin/activate'
                sh 'venv/bin/python3 -m pip install -r tools/cloud_functions/gcs_event_based_ingest/requirements-dev.txt'
            }
        }
        stage('unit_tests') {
            steps {
                sh 'cd tools/cloud_functions/gcs_event_based_ingest/ && ${VIRTUAL_ENV}/bin/python3 -m pytest tests -m "not IT"'
            }
        }
        stage('integration_tests') {
            steps {
                sh 'cd tools/cloud_functions/gcs_event_based_ingest/ && ${VIRTUAL_ENV}/bin/python3 -m pytest tests -m IT'
            }
        }
    }
}