pipeline {
    agent { docker { image 'python:3.8.0' } }
    environment {
        GOOGLE_APPLICATION_CREDENTIALS = credentials('service_acct')
    }
    stages {
        stage('install_requirements') {
            steps {
                sh 'python -m venv venv'
                sh 'venv/bin/python -m pip install --upgrade pip'
                sh 'venv/bin/python -m pip install -r tools/cloud_functions/gcs_event_based_ingest/requirements-dev.txt'
            }
        }
        stage('unit_tests') {
            steps {
                sh '. venv/bin/activate && cd tools/cloud_functions/gcs_event_based_ingest/ && python3 -m pytest tests -m "not IT"'
            }
        }
        stage('integration_tests') {
            steps {
                sh '. venv/bin/activate && cd tools/cloud_functions/gcs_event_based_ingest/ && python3 -m pytest tests -m IT'
            }
        }
    }
}