steps:
  ###########################################################
  # Build and deploy BigQuery assets
  ###########################################################
  - name: 'dataformco/dataform'
    dir: dataform/examples/bigquery_cicd
    entrypoint: bash
    args:
      - run.sh
    env:
      - PROJECT_ID=${PROJECT_ID}
      - BQ_LOCATION=US
      - BRANCH_NAME=${BRANCH_NAME}
      - SHORT_SHA=${SHORT_SHA}
      - _JS_BUCKET=${_JS_BUCKET}
      - _PR_NUMBER=${_PR_NUMBER}
