steps:
  ###########################################################
  # Build and deploy BigQuery assets
  ###########################################################
  - name: dataformco/dataform
    dir: dataform/examples/bigquery_cicd
    entrypoint: bash
    args:
      - run.sh
    env:
      - PROJECT_ID=${PROJECT_ID}
      - BQ_LOCATION=US
